quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.smallrye-openapi.path=/swagger

quarkus.smallrye-openapi.security-scheme=api-key
quarkus.smallrye-openapi.security-scheme-name=Authorization
quarkus.smallrye-openapi.api-key-parameter-in=header
quarkus.smallrye-openapi.api-key-parameter-name=Authorization